use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :my_app, MyAppWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [scheme: "https", host: H.env!("HOST_NAME"), port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# See https://hexdocs.pm/bamboo_smtp/Bamboo.SMTPAdapter.html#module-example-config
config :my_app, MyApp.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: H.env!("SMTP_SERVER"),
  username: H.env!("SMTP_USERNAME"),
  password: H.env!("SMTP_PASSWORD"),
  port: 587

config :rollbax,
  access_token: H.env!("ROLLBAR_ACCESS_TOKEN"),
  environment: "prod"
